### ISSUE TITLE
Error running `greynoiselabs` from_dict 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Obsecurus** [GreyNoise-Intelligence/greynoiselabs#51]
## Environment
* Enrichment Version: 
* Expected Output: 
    ```
    Expected Output Example
    ```
* Received Output: 
   ![image](https://github.com/GreyNoise-Intelligence/greynoiselabs/assets/30487781/83de2be8-1ec3-42af-960a-ec109e27a965)

## Steps to Reproduce

1.
2.
3.

**Comment by Obsecurus** [comment]
Confirmed: 
```
greynoiselabs-py3.8) ➜  greynoiselabs git:(main) greynoiselabs
Traceback (most recent call last):
  File "/Users/matt/Library/Caches/pypoetry/virtualenvs/greynoiselabs-863oIuMJ-py3.8/bin/greynoiselabs", line 3, in <module>
    from greynoiselabs.cli.main import app
  File "/Users/matt/go/src/github.com/greynoise-intelligence/greynoiselabs/src/greynoiselabs/cli/main.py", line 14, in <module>
    from greynoiselabs.api.client import Client
  File "/Users/matt/go/src/github.com/greynoise-intelligence/greynoiselabs/src/greynoiselabs/api/__init__.py", line 3, in <module>
    from .async_base_client import AsyncBaseClient
  File "/Users/matt/go/src/github.com/greynoise-intelligence/greynoiselabs/src/greynoiselabs/api/async_base_client.py", line 13, in <module>
    from .exceptions import (
  File "/Users/matt/go/src/github.com/greynoise-intelligence/greynoiselabs/src/greynoiselabs/api/exceptions.py", line 29, in <module>
    class GraphQLClientGraphQLError(GraphQLClientError):
  File "/Users/matt/go/src/github.com/greynoise-intelligence/greynoiselabs/src/greynoiselabs/api/exceptions.py", line 48, in GraphQLClientGraphQLError
    def from_dict(cls, error: dict[str, Any]) -> "GraphQLClientGraphQLError":
TypeError: 'type' object is not subscriptable
```
